### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by th3mach** [DFFspace/CryptoBlocker#12]
HI,
thank you for the work you do .. I have a problem.
I changed the script but when I run it I get this error:

You cannot call a method on a null-valued expression.
At line:1 char:1
+ $monitoredExtensions = $webClient.DownloadString("https://github.com/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo : InvalidOperation: (:) [], RuntimeException
     + FullyQualifiedErrorId : InvokeMethodOnNull

unfortunately I'm not a programmer, I was using the old script and I'd like to keep the definition list updated.

Thank you

**Comment by DFFspace** [comment]
Hi,

Can you link me the script that you are using so I can try to debug and see what's causing issue.

**Comment by DFFspace** [comment]
Ah. I see which script you're referring to. I've reverted back that change and updated the URL with my updated list URL in the PowerShell script. So that should work now. [DeployCryptoBlocker.ps1](https://github.com/DFFspace/CryptoBlocker/blob/master/DeployCryptoBlocker.ps1)

**Comment by th3mach** [comment]
Thanks a lot.. now it works
