### ISSUE TITLE
new Extensions https://twitter.com/pcrisk

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#13]
andrianov.txt
*.1iyT6bav7VyWM5
*[id-*].[*@*.*].*
*@paradisenewgenshinimpact.top*
How to Recovery.bat
*.clown
*.tuslamon
*.AnGrYTuRkEy
*.hhoo
*.APT14CHIR
pdb.txt
*.pdb
*.Darkbit
RECOVERY_DARKBIT.txt
*.hhee
*.hhmm
*.KTBR
Garsomware.txt
*.vvoo
*.vvmm

**Comment by gizmo21** [comment]
pdb could be a problematic one as it is for Pegasus, Quicken, Microsoft Visual Studio, and Palm

**Comment by DFFspace** [comment]
Thanks for the extension. I added them in.

**Comment by gizmo21** [comment]
Please correct the list:
REMOVE the newest of those cause I double posted them: 
```
andrianov.txt
*.1iyT6bav7VyWM5
```
CORRECT those two as `*  ...  *` are removed in this editor when not tagged as [CODE] 

```
*[id-*].[*@*.*].*
*@paradisenewgenshinimpact.top*
```

**Comment by DFFspace** [comment]
Corrected it
