### ISSUE TITLE
new Extensions https://twitter.com/pcrisk  - https://github.com/nexxai/CryptoBlocker/wiki/fallback-list

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#14]
+README-WARNING+.txt
*.google
*.snwkz
*.stolen
*.jron
!!!READ_ME_MEDUSA!!!.txt
*.zteqqd
*.tils
*.SHTORM
*.saw
*.iotr
*.iowd
*.ioqa

**Comment by DFFspace** [comment]
Updated the list. Thanks again!
