### ISSUE TITLE
All files blocked

### ISSUE THREAD

**Issue by AciidSn3ak3r** [DFFspace/CryptoBlocker#16]
Hi,
I used to use the original development of this script which worked fine, but recently moved to a new file server and found this fork and with an updated list.
Installed the script linked to this fork and found it blocked all files going on this file server.
Disabled CryptoBlockerGroup1 and files could now be saved.
I can't see what actually causes my files to block and under which type. 

I did add a skip list for the common files I saw being blocked. Namely pdf, xksx, docx etc. But didn't make a difference. Seems to be every file being blocked. 

Currently using Windows Server 2022. 

Ta

**Comment by AciidSn3ak3r** [comment]
Further witling down found that I have the following files to include
*.????????
*.????????? ????????????????
*.???????????
*.????????????????
*.????????????????????? ???? ??????????????.txt

However these aren't in the download list. So i'm unsure how these are getting in. Other language characters perhaps? 
Removing these allow me to save files again.

**Comment by DFFspace** [comment]
Hello,

That's some strange behavior. I do use this list as well and haven't seen any issues so far on my Windows Server 2022. I also make use of my own PowerShell script.

I also haven't touched the DeployCryptoBlocker.ps1 file other than reverting a change back to it's original to retrieve the extensions again as seen here. #12

**Comment by AciidSn3ak3r** [comment]
Peculiar. Only other things I can think of which might make my environment different is i'm based in the UK. 
Not really sure what else it could be though. But definitely removing those entries returns it into a working state.

**Comment by DFFspace** [comment]
Could it maybe be some sort of setting? I haven't really looked in to how the script works. In our environment we manually created the whole FSRM and only I only created a script that would add and or update the extension list when it does it's daily check to see if there are any new extensions being added. 

I can look If I can trim down the script I use. It has loads of HTML code to generate a e-mail that I could trim out and make it basic.
![Screenshot 2023-03-08 105028](https://user-images.githubusercontent.com/69241933/223680788-800b3455-bbaf-4a4f-9b28-c9835a2c7b9c.png)

**Comment by AciidSn3ak3r** [comment]
I didn't let the script install FSRM. This was already installed. The script just created the groups, downloaded the list and then blocked everything due to those entries. 
Could it be a setting? Maybe. No idea what though

**Comment by DFFspace** [comment]
I've added my simplified script creating and updating the extensions in a File Group.

https://github.com/DFFspace/CryptoBlocker/blob/master/AddFSRMFileGroup.ps1

Also something I was wondering you mentioned it blocking all files? Could it be using all the default File Groups?
![image](https://user-images.githubusercontent.com/69241933/224277952-d6d7b9aa-9d8c-498e-ab03-a19dfc63a874.png)

I only use the Known Ransomware Files in my File Screening.
![image](https://user-images.githubusercontent.com/69241933/224278215-25d35523-56ae-4012-a08d-3195c4bd016a.png)

**Comment by DFFspace** [comment]
Hello @AciidSn3ak3r,

Please have a look at: https://github.com/nexxai/CryptoBlocker/issues/104#issuecomment-1477832122 Think we found what causing the issue.

**Comment by DFFspace** [comment]
Hello @madeyem!

Thanks for reaching out. I have just made some changes in the https://github.com/DFFspace/CryptoBlocker/blob/master/DeployCryptoBlocker.ps1 script, that should fix the issue were it is blocking all files.

Let me know if that works for you.

**Comment by madeyem** [comment]
Hi @DFFspace,
thank you!

In line 210 shouldn't it be $KnownExtensionsListURL instead of $UpdateURL?

**Comment by DFFspace** [comment]
Thanks for pointing that out. Fixed it!

**Comment by madeyem** [comment]
Script looks good now, "All files blocked" is not happening any more.
Thank you @DFFspace!
