### ISSUE TITLE
new extensions - https://twitter.com/pcrisk #19

### ISSUE THREAD

**Issue by pmadtaylor** [DFFspace/CryptoBlocker#19]
*.kmufesd
*.basn
*.Merlin
*.usr

**Comment by gizmo21** [comment]
thx alot @pmadtaylor for joining here and there https://github.com/nexxai/CryptoBlocker/wiki/fallback-list 
only two more then for me:

*.dazx
*.dapo

**Comment by DFFspace** [comment]
Updated the list. Thanks both!
