### ISSUE TITLE
Remove wildcard entries

### ISSUE THREAD

**Issue by philipcole88** [DFFspace/CryptoBlocker#201]
We use the Known Extensions List to import this into a Windows File Server Resource Manager File Group for screening potential malicious files.
The below entries are treated as wildcards and pick up basically any file extention which causes all files with any extension to be blocked.
Could we please remove the below file extensions from this list:

*.?????????
*.?????????? ????????????????????????
*.????????????
*.????????????
*.????????????????
*.???????????????????? ???? ????????????.txt

**Comment by DFFspace** [comment]
Heya, this seems super familiar seen in issue #16 where they had a similar pattern of all files being blocked. It had something to do with the Deserializes JSON input into PowerShell object output. And made some changes to the script like here to solve it: https://github.com/DFFspace/CryptoBlocker/commit/79fe05626a6d763870eff8ff078ab1f528eb693b

**Comment by philipcole88** [comment]
Thanks. I did initially try updating the Invoke-WebRequest section of the script to use 'Invoke-WebRequest $url -UseBasicParsing -ContentType 'application/json; charset=UTF-8' but that didnt end up working.
Checking over your current update of the script and changing it to the below worked for me:

((Invoke-WebRequest -Uri $KnownExtensionsListURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

Thanks!

**Comment by DFFspace** [comment]
Glad that it is working!
