### ISSUE TITLE
New Extensions - PCRisk

### ISSUE THREAD

**Issue by pmadtaylor** [DFFspace/CryptoBlocker#22]
*.random_string@BLOCKED
*.tyos
*.typo

**Comment by DFFspace** [comment]
Added the above extension to the list. Thanks!

**Comment by gizmo21** [comment]
.random_string@BLOCKED
should rather be 
``*.*@BLOCKED``
see: https://www.pcrisk.com/removal-guides/26382-at-sign-blocked-ransomware

**Comment by DFFspace** [comment]
I've updated the extension. Thanks!
