### ISSUE TITLE
new Extensions - pcrisk

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#26]
*.Hairysquid
*.sus

and *.skynet was an extension which was already on the list , round about here:
*.info@mymail9[dot]com
*.skynet
*.sapphire

**Comment by pmadtaylor** [comment]
I gaffed on that.  Normally I search first before posting, but I forgot.

**Comment by DFFspace** [comment]
Added the new extensions and fixed the duplication of ***.skynet** removing it from line 7. Thanks!

Seems there are some more duplicates that I found with my workflow action:

```*.carone [44, 219]
*.consultransom [45, 218]
*.devicZz [46, 217]
*.FARGO3 [49, 220]
*.726 [70, 4201]
*.725 [203, 4218]
*.znto [223, 236]
*.bpws [226, 242]
*.btos [273, 2324]
*.support@anonymous-service.cc.ppdddp [831, 2400]
```
I will clean them up.

I 'am also working on a workflow combining this so it notifies / fails the build in case of a duplicate.
