### ISSUE TITLE
new extensions - https://twitter.com/pcrisk

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#3]
*.mzop
*.marnet2
*.rdapdylvb
*.mzqw
*.BoY
*.STEEL
*.ENCODED
*.GOGO
*.725
covid29-is-here.txt
*.FinD0m
*.secured
*.tzw
*.NYX
*.xollam
*.Zendaya
*.G-Stars
*.Encrypto

**Comment by DFFspace** [comment]
Added them to the list, thank you!
