### ISSUE TITLE
.pdf ??

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#4]
there is another new one, but as it is .pdf it could be potentially harmful for some environments:
https://twitter.com/pcrisk/status/1614865574797971456

you could go with this one:
`*.id-*.[*@*.*].pdf`

or a bit more strict:
https://www.virustotal.com/gui/file/5cbbb9e5c138fcf8fb4de3ecab3c1028a668c2560323b1ce43fda99514cb20ce/behavior
`*.id-*.[*@qq.com].pdf`

or pass it completely

**Comment by gizmo21** [comment]
Nevermind, this was already included in the list, so it seems the localmail-part doesn't change on different victims:
*.id-*.[3442516480@qq.com].pdf

**Comment by DFFspace** [comment]
@gizmo21, Do I need to change something or all good?

**Comment by gizmo21** [comment]
the exact same is already included. So no addition needed as pdf is tricky. everyone can add it for their own environment if possible.
