### ISSUE TITLE
Issue with CryptoBlockerGroup1

### ISSUE THREAD

**Issue by jchileski** [DFFspace/CryptoBlocker#44]
Something the script loads into CryptoBlockerGroup1 triggers my environment to disallow any sort of file, aside from folders, to be saved in the monitored shares. Anyone have any thoughts? Script used to deploy is default script with the pull url modified to this one.

Turning to monitor as opposed to block allows files to be saved, and deleting cryptoblockergroup1 entirely also allows files to be saved.

**Comment by DFFspace** [comment]
Which script are you using? I saw that other people had issues where it blocked all files. This has something to do with it not being able to handle certain characters properly.

In this forked repo, I have modified the script to fix these issues: https://github.com/DFFspace/CryptoBlocker/blob/master/DeployCryptoBlocker.ps1 

Also see issue #16

**Comment by jchileski** [comment]
Ahhh,

I was apending the original script, my bad. Will try this and see what it amounts to. Much appreciated!

**Comment by jchileski** [comment]
Can confirm this was the issue and it works properly now. Thank you!

**Comment by DFFspace** [comment]
Glad it works!
