### ISSUE TITLE
extensions https://twitter.com/splinter_code and https://twitter.com/siri_urz

### ISSUE THREAD

**Issue by gizmo21** [DFFspace/CryptoBlocker#5]
*.royal_w
*.canadian
*.buddyransome
*.v1cesO0ciety
`AllYFilesAE*`
*.Amelia
*.Vohuk
*.seiv
*.RedAlert
*.cpyt
*.tprc
*.cprt
*.BlackHunt
*.rippc
*.Zakaz
*.ElbeeCrypt
*.Blackmagic

**Comment by DFFspace** [comment]
I added them all in. Thanks again!
