### ISSUE TITLE
Question about AddFSRMFileGroup.ps1

### ISSUE THREAD

**Issue by Samsonait** [DFFspace/CryptoBlocker#52]
Question about the simplified version, its great!

How would you add an -ExcludePattern? I have 1 particular pattern which is .lck which is used by an Database on a production server.
So when i update, i want to exclude a particular patern automaticly.

Is that possible? And which line would you add?
Richt now: -ExcludePattern @("*.lck")

Is creating a system error for me, without the line its working perfect

**Comment by DFFspace** [comment]
Something you could try is the following code:

```PowerShell
# Define variables
$ErrorLog          = "C:\FSRMscript\Error\FSRMscript.txt"
$DateTime          = Get-Date
$UpdateURL         = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
$FsrmFileGroupName = "Known Ransomware Files"
$Logfile           = $ErrorLog

Function LogWrite {
    Param ([string]$logstring)
    Add-Content $Logfile -Value $logstring -Encoding UTF8
}

try {
    # Get last updated date
    LogWrite "Fetching last updated date from $UpdateURL ..."
    $LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
    $Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))

    # Get extensions
    LogWrite "Fetching list of extensions from $UpdateURL ..."
    $Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

    # Check if file group exists, update or create file group accordingly
    if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
        LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
        $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
        $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
        $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
        $listExclude = $FSRMgroup.ExcludePattern + @("*.lck")
        Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
    }
    else {
        LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
        New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern "*.lck" -ErrorAction Stop | Out-Null
        $NewExtensions = $Extensions | Sort-Object
    }

    LogWrite "Script completed successfully."
}
catch {
    $ErrorMessage = $_.Exception.Message
    Write-Host -ForegroundColor Yellow $ErrorMessage
    LogWrite "$($DateTime) - ERROR: $ErrorMessage"
}

```

**Comment by Samsonait** [comment]
> Something you could try is the following code:
> 
> ```powershell
> # Define variables
> $ErrorLog          = "C:\FSRMscript\Error\FSRMscript.txt"
> $DateTime          = Get-Date
> $UpdateURL         = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
> $FsrmFileGroupName = "Known Ransomware Files"
> $Logfile           = $ErrorLog
> 
> Function LogWrite {
>     Param ([string]$logstring)
>     Add-Content $Logfile -Value $logstring -Encoding UTF8
> }
> 
> try {
>     # Get last updated date
>     LogWrite "Fetching last updated date from $UpdateURL ..."
>     $LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
>     $Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))
> 
>     # Get extensions
>     LogWrite "Fetching list of extensions from $UpdateURL ..."
>     $Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters
> 
>     # Check if file group exists, update or create file group accordingly
>     if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
>         LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
>         $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
>         $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
>         $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
>         $listExclude = $FSRMgroup.ExcludePattern + @("*.lck")
>         Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
>     }
>     else {
>         LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
>         New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern "*.lck" -ErrorAction Stop | Out-Null
>         $NewExtensions = $Extensions | Sort-Object
>     }
> 
>     LogWrite "Script completed successfully."
> }
> catch {
>     $ErrorMessage = $_.Exception.Message
>     Write-Host -ForegroundColor Yellow $ErrorMessage
>     LogWrite "$($DateTime) - ERROR: $ErrorMessage"
> }
> ```

I will try! And if i add new extensions to that, is it comma seperated? @("*.lck","*.one")
Or like this: @("*.lck")@("*.one")

**Comment by DFFspace** [comment]
Yes you could even define a variable at the top if you want to make it a bit easier. 

Like this: `$ExcludeExtensions = @("*.lck", "*.one")`

Than define it like @($ExcludeExtensions) at the `$FSRMgroup.ExcludePattern +` line should do the trick.

**Comment by DFFspace** [comment]
Hmmm....

I have ran a test on my test VM and seems to work as expected. Here is the code that I used for it:

```PowerShell
# Define variables
$ErrorLog          = "C:\FSRMscript\Error\FSRMscript.txt"
$DateTime          = Get-Date
$UpdateURL         = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
$FsrmFileGroupName = "Known Ransomware Files"
$Logfile           = $ErrorLog
$ExcludeExtension  = @(".lck", ".one")

Function LogWrite {
    Param ([string]$logstring)
    Add-Content $Logfile -Value $logstring -Encoding UTF8
}

try {
    # Get last updated date
    LogWrite "Fetching last updated date from $UpdateURL ..."
    $LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
    $Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))

    # Get extensions
    LogWrite "Fetching list of extensions from $UpdateURL ..."
    $Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

    # Check if file group exists, update or create file group accordingly
    if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
        LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
        $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
        $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
        $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
        $listExclude = $FSRMgroup.ExcludePattern + @($ExcludeExtension)
        Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
    }
    else {
        LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
        New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern $ExcludeExtension -ErrorAction Stop | Out-Null
        $NewExtensions = $Extensions | Sort-Object
    }

    LogWrite "Script completed successfully."
}
catch {
    $ErrorMessage = $_.Exception.Message
    Write-Host -ForegroundColor Yellow $ErrorMessage
    LogWrite "$($DateTime) - ERROR: $ErrorMessage"
}
```

![image](https://github.com/DFFspace/CryptoBlocker/assets/69241933/ffabb57d-68a4-4687-9c36-0c0dfef6f1a9)

**Comment by Samsonait** [comment]
I think i had a typo somewhere, its working like a charm.
Thanks bro!

**Comment by Samsonait** [comment]
Hey man, i need to reopen this.
Can you help me with the following?

The Files to exclude are also in the include which is causing it to break.
Also it gets double entrys

Im using the code above, but after running the powershell from a task shedule i get double entries
See:

![afbeelding](https://github.com/DFFspace/CryptoBlocker/assets/39726588/fe819aad-3171-4587-a1a2-1789c2507ef0)

**Comment by Samsonait** [comment]
I feel like i also have to do this
 $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object****

but then also with the exclude?

**Comment by Samsonait** [comment]
> That's odd.... I'll be running some tests and debugs later to see what causes this.

Much appreciated man! Anywhere i can buy you a cup of coffee?

**Comment by DFFspace** [comment]
From my tests I noticed that the only issue seems to be adding duplicates of the excluded extensions. The other error message where it tells you that it can't have both in include or exclude is normal cause you cannot have both extensions in the include and exclude pattern. That would be strange if they allowed it to happen haha. 

From my tests the above code does not add the exclude extensions to the include pattern but it does seems to duplicate the excluded extensions on every run. I will look what causes this. I have noticed this to with only using the included extension when I have a extension but it has a typo, when I fix the typo it keeps duplicating the extension that had the typo.

**Comment by DFFspace** [comment]
```PowerShell
# Define variables
$ErrorLog          = "C:\FSRMscript\Error\FSRMscript.txt"
$DateTime          = Get-Date
$UpdateURL         = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
$FsrmFileGroupName = "Known Ransomware Files"
$Logfile           = $ErrorLog
$ExcludeExtension  = @("*.lck", "*.one")

Function LogWrite {
    Param ([string]$logstring)
    Add-Content $Logfile -Value $logstring -Encoding UTF8
}

try {
    # Get last updated date
    LogWrite "Fetching last updated date from $UpdateURL ..."
    $LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
    $Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))

    # Get extensions
    LogWrite "Fetching list of extensions from $UpdateURL ..."
    $Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

    # Check if file group exists, update or create file group accordingly
    if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
        LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
        $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
        $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
        $NewExcludeExtension = Compare-Object -ReferenceObject $ExcludeExtension -DifferenceObject $FSRMgroup.ExcludePattern -PassThru | Sort-Object
        $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
        $listExclude = $FSRMgroup.ExcludePattern + @($NewExcludeExtension)
        Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
    }
    else {
        LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
        New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern $ExcludeExtension -ErrorAction Stop | Out-Null
        $NewExtensions = $Extensions | Sort-Object
    }

    LogWrite "Script completed successfully."
}
catch {
    $ErrorMessage = $_.Exception.Message
    Write-Host -ForegroundColor Yellow $ErrorMessage
    LogWrite "$($DateTime) - ERROR: $ErrorMessage"
}
```

This should solve it. You where in the right direction with adding one for the exclude to haha.

`$listExclude = $FSRMgroup.ExcludePattern + @($ExcludeExtension)` by running that it just kept adding them over and over when it runs. 

`$NewExcludeExtension = Compare-Object -ReferenceObject $ExcludeExtension -DifferenceObject $FSRMgroup.ExcludePattern -PassThru | Sort-Object` adding this and changing this `$listExclude = $FSRMgroup.ExcludePattern + @($NewExcludeExtension)` solves this.

**Comment by Samsonait** [comment]
Nice! I dont get doubles!

Do you also still have that they put the extension in the include - and - exclude?
![afbeelding](https://github.com/DFFspace/CryptoBlocker/assets/39726588/94709bf7-302e-45b5-8840-b7e552c9a120)


I deleted the entire ransomware list (except 1 because it wants 1 in there)
i re-ran the script, and still it ads it in the include, and the exclude lol

And you still havent told me where i can buy you an coffee, do you take donations?

**Comment by DFFspace** [comment]
Can you share the script that you are using with your scheduled task? 

And I don't take any donations haha.

**Comment by Samsonait** [comment]
#Ontwikkeld door Noël Hielkema
#Laatst bijgewerkt 16-6-2023

# Define variables
$ErrorLog          = "C:\Services\Ransomware\FSRMscript.txt"
$DateTime          = Get-Date
$UpdateURL         = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
$FsrmFileGroupName = "Ransomware"
$Logfile           = $ErrorLog
$ExcludeExtension  = @("*.lck", "*.one", "*.tro", "*.szf")


#Forceert TLS12 voor een veilige pull
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Function LogWrite {
    Param ([string]$logstring)
    Add-Content $Logfile -Value $logstring -Encoding UTF8
}

try {
    # Get last updated date
    LogWrite "Fetching last updated date from $UpdateURL ..."
    $LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
    $Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))

    # Get extensions
    LogWrite "Fetching list of extensions from $UpdateURL ..."
    $Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

    # Check if file group exists, update or create file group accordingly
    if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
        LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
        $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
        $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
        $NewExcludeExtension = Compare-Object -ReferenceObject $ExcludeExtension -DifferenceObject $FSRMgroup.ExcludePattern -PassThru | Sort-Object
        $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
        $listExclude = $FSRMgroup.ExcludePattern + @($NewExcludeExtension)
        Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
    }
    else {
        LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
        New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern $ExcludeExtension -ErrorAction Stop | Out-Null
        $NewExtensions = $Extensions | Sort-Object
    }

    LogWrite "Script completed successfully."
}
catch {
    $ErrorMessage = $_.Exception.Message
    Write-Host -ForegroundColor Yellow $ErrorMessage
    LogWrite "$($DateTime) - ERROR: $ErrorMessage"
}

#Mailing 

Send-MailMessage -From ransomwareupdate@ltonoord.nl -Subject "Update geslaagd op $env:COMPUTERNAME" -To ict@ltonoord.nl -Body "Nieuwe Ransomware groep update geslaagd op $env:COMPUTERNAME " -BodyAsHtml -DeliveryNotificationOption OnSuccess -SmtpServer 192.168.1.9

**Comment by DFFspace** [comment]
Looks like the extensions that you are excluding seem to appear in the KnownExtensions list as well. So that seems to be the issue where it adds them to both.

```powershell
$ErrorLog = "C:\Services\Ransomware\FSRMscript.txt"
$DateTime = Get-Date
$UpdateURL = "https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/KnownExtensions.txt"
$FsrmFileGroupName = "Ransomware"
$Logfile = $ErrorLog
$ExcludeExtension = @("*.lck", "*.one", "*.tro", "*.szf")

#Forceert TLS12 voor een veilige pull
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Function LogWrite {
Param ([string]$logstring)
Add-Content $Logfile -Value $logstring -Encoding UTF8
}

try {
# Get last updated date
LogWrite "Fetching last updated date from $UpdateURL ..."
$LastUpdated = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).lastupdated
$Date = $LastUpdated.Substring(0, $LastUpdated.LastIndexOf('T'))

# Get extensions
LogWrite "Fetching list of extensions from $UpdateURL ..."
$Extensions = ((Invoke-WebRequest -Uri $UpdateURL -ErrorAction Stop).Content | ConvertFrom-Json).filters

# Remove excluded extensions from extensions list
foreach ($exclude in $ExcludeExtension) {
    $Extensions = $Extensions | Where-Object { $_ -notlike $exclude }
}

# Check if file group exists, update or create file group accordingly
if (Get-FsrmFileGroup -Name $FsrmFileGroupName -ErrorAction SilentlyContinue) {
    LogWrite "File group '$FsrmFileGroupName' already exists. Updating include and exclude patterns ..."
    $FSRMgroup = Get-FsrmFileGroup $FsrmFileGroupName
    $NewExtensions = Compare-Object -ReferenceObject $Extensions -DifferenceObject $FSRMgroup.IncludePattern -PassThru | Sort-Object
    $NewExcludeExtension = Compare-Object -ReferenceObject $ExcludeExtension -DifferenceObject $FSRMgroup.ExcludePattern -PassThru | Sort-Object
    $listInclude = $FSRMgroup.IncludePattern + @($NewExtensions)
    $listExclude = $FSRMgroup.ExcludePattern + @($NewExcludeExtension)
    Set-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $listInclude -ExcludePattern $listExclude
}
else {
    LogWrite "Creating new file group '$FsrmFileGroupName' with include and exclude patterns ..."
    New-FsrmFileGroup -Name $FsrmFileGroupName -IncludePattern $Extensions -ExcludePattern $ExcludeExtension -ErrorAction Stop | Out-Null
    $NewExtensions = $Extensions | Sort-Object
}

LogWrite "Script completed successfully."
}
catch {
$ErrorMessage = $_.Exception.Message
Write-Host -ForegroundColor Yellow $ErrorMessage
LogWrite "$($DateTime) - ERROR: $ErrorMessage"
}

#Mailing

Send-MailMessage -From ransomwareupdate@ltonoord.nl -Subject "Update geslaagd op $env:COMPUTERNAME" -To ict@ltonoord.nl -Body "Nieuwe Ransomware groep update geslaagd op $env:COMPUTERNAME " -BodyAsHtml -DeliveryNotificationOption OnSuccess -SmtpServer 192.168.1.9```

I have added some code that should remove them from the `$Extensions`  Line 26 to 29 has been added and I have added `*` to the ExcludeExtensions.

**Comment by Samsonait** [comment]
Now a weird thing happens, instead of excluding them i get 2 of them in the Include LOL

![afbeelding](https://github.com/DFFspace/CryptoBlocker/assets/39726588/3a6b46b5-4660-4f35-b403-ae1e10551d25)

**Comment by Samsonait** [comment]
Deleting and re-adding solved the issue m8

You wont let me give you a cup of coffee, so i just have to thank you

Thanks man!

**Comment by DFFspace** [comment]
No problem!
